stages:
  - deploy-specific
  - deploy-virtual

services:
  - name: docker:19.03.8-dind
    alias: docker-in-docker

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker-in-docker:2375/
  DOCKER_REGISTRY: proteinqure

build-py38:
  image: proteinqure/basic-ci
  stage: deploy-specific
  script:
    - dnf install -y make
    - make py38

build-py39:
  image: proteinqure/basic-ci
  stage: deploy-specific
  script:
    - dnf install -y make
    - make py39

build-virtual:
  image: proteinqure/basic-ci
  stage: deploy-virtual
  script:
    - dnf install -y make
    - python3 -m ensurepip
    - python3 -m pip install twine wheel
    - RDKIT_VERSION=2020.9.5 make virtual
