stages:
  - deploy

services:
  - name: docker:19.03.8-dind
    alias: docker-in-docker

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker-in-docker:2375/
  DOCKER_REGISTRY: proteinqure

build-py36:
  image: proteinqure/basic-ci
  stage: deploy
  script:
    - dnf install -y make
    - make py36

build-py37:
  image: proteinqure/basic-ci
  stage: deploy
  script:
    - dnf install -y make
    - make py37

build-py38:
  image: proteinqure/basic-ci
  stage: deploy
  script:
    - dnf install -y make
    - make py38

build-py39:
  image: proteinqure/basic-ci
  stage: deploy
  script:
    - dnf install -y make
    - make py39
